apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: secrets
spec:
  type: secretstores.local.file
  version: v1
  metadata:
    # secretsFile path needs to relative to where the "dapr run" command is invoked or an absolute path.
    - name: secretsFile
      value: ./.dapr/components/secrets.json
    - name: nestedSeparator
      value: ":"
    - name: multiValued
      value: "false"
scopes:
  - users-api
  - articles-api